### PR TITLE
Re-factor into a collection

### PR DESCRIPTION
**Pull request by mariolenz**
Since Ansible 2.9, the standard way to distribute ansible content are [collections](https://docs.ansible.com/ansible/2.9/dev_guide/developing_collections.html). I've started to re-factor your code into one.

There are still some things to do, especially updating the documentation. Oh, and there are some problems with the unit tests of `idrac_os_deployment` and `redfish_storage_volume` but I'm not sure if this is really caused by the re-factoring or if the problems existed before.

Well, the [devel branch corresponds to the release actively under development](https://github.com/dell/dellemc-openmanage-ansible-modules/blob/58390341fbcbe6cecfae76acee4f1a6b466602f0/README.md) so it should be OK if it's in a state that's not production ready. We can work together on improving the collection after you've accepted this PR.

### CODE REVIEW

**Comment by jagadeeshnv** [comment]
Hi @mariolenz, We are looking into this, will get back.

**Comment by mariolenz** [comment]
> Hi @mariolenz, We are looking into this, will get back.

It still needs some polishing (or maybe even a lot) but it's a start. And, of course, I can see there's a lot to discuss because it's a breaking change. Like how to transition to this new delivery model and do you want to support both ways for some time? For example, release a collection as the new 3.0 version but still support the old code base for some time or have a hard cut?

There are quite a lot of commits, but that's intentional: I hope it's easier to understand what I did this way. Committing everything in one go would possibly be a bit too complex.

**Comment by jagadeeshnv** [comment]
Hi @mariolenz, 
We created a new branch "collections" please submit it against that branch so that we can move forward.

**Comment by mariolenz** [comment]
> We created a new branch "collections" please submit it against that branch so that we can move forward.

#128

**Pull request closed without merging**
