### PR TITLE
[idrac_reset] - Fixing issue #652

### LINKED ISSUE #569: [QUESTION]: Factory Reset iDRAC & wait_for_idrac?
### How can the team help?
We'd like to do the following in a single playbook:
1. Factory Reset BIOS Settings
2. Factory Reset iDRAC via **reset_to_default: "ALL"** (including network & user)
3. Change Root Password

## Issue: 
When resetting the iDRAC to default root password back to 'calvin', we can't use  **dellemc.openmanage.idrac_reset** with **wait_for_idrac: True** to guarantee the iDRAC is ready before we try to reset the password since the credentials used to call the role are different half way through execution.

## Question: 
Is there an easy way to call the [lcstatuscheck](https://github.com/dell/dellemc-openmanage-ansible-modules/blob/collections/roles/idrac_reset/tasks/lcstatus_check.yml) Task separately before Change Root Password or is there an example of how to call the URI **/redfish/v1/Dell/Managers/iDRAC.Embedded.1/DellLCService/Actions/DellLCService.GetRemoteServicesAPIStatus** on its own? 

### Playbook
```yaml
- hosts: '{{ host }}'
  gather_facts: false
  tasks:
    - name: Factory Reset Dell BIOS
      dellemc.openmanage.idrac_bios:
        idrac_ip: '{{ idrac_ip }}'
        idrac_password: '{{ idrac_password }}'
        idrac_user: '{{ idrac_user }}'
        validate_certs: False
        reset_bios: yes
      delegate_to: localhost

    - name: Factory Reset the iDRAC (keep network and user settings) and wait for the idrac to be ready
      ansible.builtin.include_role:
        name: dellemc.openmanage.idrac_reset       
      vars:
        hostname: '{{ idrac_ip }}'
        username: '{{ idrac_user }}'
        password: '{{ idrac_password }}'
        reset_to_default: "All"
        validate_certs: False
        wait_for_idrac: False # Wish this could be True

   - name: Change Root Password
     community.general.idrac_redfish_config:
       category: Manager
       command: SetManagerAttributes
       manager_attributes:
         Users.2.AuthenticationProtocol: "SHA"
         Users.2.EmailAddress: ""
         Users.2.Enable: "Enabled"
         Users.2.IpmiLanPrivilege: "Administrator"
         Users.2.IpmiSerialPrivilege: "Administrator"
         Users.2.Password: "{{ idrac_password }}"
         Users.2.PrivacyProtocol: "AES"
         Users.2.Privilege: 511
         Users.2.ProtocolEnable: "Disabled"
         Users.2.Simple2FA: "Disabled"
         Users.2.SolEnable: "Enabled"
         Users.2.UseEmail: "Disabled"
         Users.2.UserName: "root"
       baseuri: "{{ idrac_ip }}"
       username: "{{ idrac_user }}"
       password: "calvin"
     delegate_to: localhost
```

### LINKED ISSUE #652: [BUG]: idrac_reset fails when idrac is InUse state
### Bug Description

issue started recently - used to work without any problems in the past - i started observing this in collection 9.2.0
we run deployment from ISO where ISO is mounted for default 120min
as deployments usually finish faster, we have process to reset idrac in order to unmount the ISO from iDrac after deployment is done
recently we started getting error "Lifecycle controller status check is InUse after 50 number of retries, Exiting.."

### Component or Module Name

idrac_reset

### Ansible Version

2.16.6

### Python Version

Python 3.11.7

### iDRAC/OME/OME-M version

IDRAC 7.00.00.171(Build 05) 

### Operating System

Linux OS

### Playbook Used

- name: "Reset iDRAC"
          dellemc.openmanage.idrac_reset:
            idrac_ip: "{{ lom_ip }}"
            idrac_user: "{{ lom_username }}"
            idrac_pwd: "{{ lom_password }}"
            validate_certs: false
          register: idrac_reset_result

### Logs
``{
    "msg": "Lifecycle controller status check is InUse after 50 number of retries, Exiting..",
    "invocation": {
        "module_args": {
            "idrac_ip": "10..10.10.10",
            "idrac_user": "root",
            "idrac_pwd": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "validate_certs": false,
            "idrac_password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "wait_for_idrac": true,
            "job_wait_timeout": 600,
            "force_reset": false,
            "idrac_port": 443,
            "timeout": 30,
            "reset_to_default": null,
            "custom_defaults_file": null,
            "custom_defaults_buffer": null,
            "ca_path": null
        }
    },
    "_ansible_no_log": false,
    "changed": false,
    "_ansible_delegated_vars": {
        "ansible_host": "localhost",
        "ansible_port": null,
        "ansible_user": "user",
        "ansible_connection": "local"
    }
}`
`
### Steps to Reproduce

run task to  put idrac into the InUse state 
run task to try reset idrac

### Expected Behavior

expected is to have idrac reset 

### Actual Behavior

error message - Lifecycle controller status check is InUse after 50 number of retries, Exiting..
and module fail state

### Screenshots

_No response_

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by ABHISHEK-SINHA10**
# Description
A few sentences describing the overall goals of the pull request's commits.

# GitHub Issues
List the GitHub issues impacted by this PR:

| GitHub Issue # |
| -------------- |
| |

# ISSUE TYPE

- Bugfix Pull Request
- Docs Pull Request
- Feature Pull Request
- Test Pull Request

##### OUTPUT

```paste below

```
##### ADDITIONAL INFORMATION

```paste below

```
# Checklist:

- [ ] I have performed a self-review of my own code to ensure there are no formatting, vetting, linting, or security issues
- [ ] I have verified that new and existing unit tests pass locally with my changes
- [ ] I have not allowed coverage numbers to degenerate
- [ ] I have maintained at least 90% code coverage
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have maintained backward compatibility

### CODE REVIEW

**Comment by ansible-collections-svc** [comment]
Can one of the admins verify this patch?

**Review by Kritika-Bhateja-03 — APPROVED** [review]

**Review by rajshekarp87 — DISMISSED** [review]

**Review by ShivamSh3 — APPROVED** [review]

**Comment by ABHISHEK-SINHA10** [comment]
image


UT Coverage

**Comment by singh-lovepreet1** [comment]
Can we also update 'retVal' in the output to 'retval' that is being specified in the specs?

**Comment by singh-lovepreet1** [comment]
Can we also update existing examples according to the discussion?

**Comment by sachin-apa** [comment]
run e2e

**Review by singh-lovepreet1 — APPROVED** [review]

**Review by sachin-apa — APPROVED** [review]

**Review by rajshekarp87 — APPROVED** [review]

**Pull request merged**
