### PR TITLE
[Roles/Playbooks] Fixed lint issues in roles and playbooks

### LINKED ISSUE #514: [BUG]: File copy/access issue during idrac_os_deployment kickstart part
### Bug Description

When running the playbook, everything seems to go fine until it gets to copy some files. I have tried to run it with and without become: true and am getting similar results. Both scenario logs are included.

I am still learning and this is basically the first playbook i have chopped together for playing around so please ignore that i have all the variables in the playbook, not separate.

### Component or Module Name

idrac_os_deployment

### Ansible Version

2.15.1

### Python Version

3.9.16

### iDRAC/OME/OME-M version

iDRAC 7.00.00.00

### Operating System

Rocky Linux 9.2

### Playbook Used

- name: Generate custom iso using a kickstart file and install vSphere
  hosts: idrac
  become: true
  connection: local
  roles:
    - dellemc.openmanage.idrac_os_deployment
  vars:
    hostname: X.X.X.X
    username: root
    password: test
    os_name: ESXI
    os_version: 8.x
    esxi_rootpw: test
    validate_certs: false
    source:
      is_custom_iso: false
      protocol: local
      hostname: localhost
      iso_path: /home/myuser/Documents/ 
      iso_name: VMware-VMvisor-Installer-8.0U1a-21813344.x86_64.iso  
    destination:  
      protocol: nfs
      hostname: X.X.Y.Y
      mountpoint: /home/myuser/nfss # mounted this beforehand
      os_type: linux
      iso_path: /home/nfsserver/nfs/share/
      username: test
      password: test

### Logs

**With become: true**

`TASK [dellemc.openmanage.idrac_os_deployment : Report task failure] **************************************************************************************************************************************************************************
task path: /home/myuser/.ansible/collections/ansible_collections/dellemc/openmanage/roles/idrac_os_deployment/tasks/main.yml:65
fatal: [X.X.X.X]: FAILED! => {
    "failed_when_result": true,
    "idrac_os_deployment_failure": {
        "changed": false,
        "exception": "Traceback (most recent call last):\n  File \"/home/myuser/.local/lib/python3.9/site-packages/ansible/plugins/action/copy.py\", line 466, in run\n    source = self._find_needle('files', source)\n  File \"/home/myuser/.local/lib/python3.9/site-packages/ansible/plugins/action/__init__.py\", line 1455, in _find_needle\n    return self._loader.path_dwim_relative_stack(path_stack, dirname, needle)\n  File \"/home/myuser/.local/lib/python3.9/site-packages/ansible/parsing/dataloader.py\", line 341, in path_dwim_relative_stack\n    raise AnsibleFileNotFound(file_name=source, paths=[to_native(p) for p in search])\nansible.errors.AnsibleFileNotFound: Could not find or access '/tmp/omam_osdan1rzd2h/kickstart_ESXI_X.X.X.X.cfg' on the Ansible Controller.\nIf you are using a module and expect the file to exist on the remote, see the remote_src option\n",
        "failed": true,
        "failed_task_name": "Copy KS file to extracted directory",
        "invocation": {
            "dest": "/tmp/omam_osdan1rzd2h/extract/KS.CFG",
            "mode": "0744",
            "module_args": {
                "dest": "/tmp/omam_osdan1rzd2h/extract/KS.CFG",
                "mode": "0744",
                "src": "/tmp/omam_osdan1rzd2h/kickstart_ESXI_X.X.X.X.cfg"
            },
            "src": "/tmp/omam_osdan1rzd2h/kickstart_ESXI_X.X.X.X.cfg"
        },
        "msg": "Could not find or access '/tmp/omam_osdan1rzd2h/kickstart_ESXI_X.X.X.X.cfg' on the Ansible Controller.\nIf you are using a module and expect the file to exist on the remote, see the remote_src option"
    }
}`

**Without become: true**

`TASK [dellemc.openmanage.idrac_os_deployment : Append ks path to the linux boot menu] ********************************************************************************************************************************************************
task path: /home/myuser/.ansible/collections/ansible_collections/dellemc/openmanage/roles/idrac_os_deployment/tasks/esxi/compile_iso.yml:9
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: myuser
<localhost> EXEC /bin/sh -c 'echo ~myuser && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/myuser/.ansible/tmp `"&& mkdir "` echo /home/myuser/.ansible/tmp/ansible-tmp-1690445270.4359188-1858013-196186863923399 `" && echo ansible-tmp-1690445270.4359188-1858013-196186863923399="` echo /home/myuser/.ansible/tmp/ansible-tmp-1690445270.4359188-1858013-196186863923399 `" ) && sleep 0'
Using module file /home/myuser/.local/lib/python3.9/site-packages/ansible/modules/lineinfile.py
<localhost> PUT /home/myuser/.ansible/tmp/ansible-local-1856648k75z5x5j/tmpfx35d9bn TO /home/myuser/.ansible/tmp/ansible-tmp-1690445270.4359188-1858013-196186863923399/AnsiballZ_lineinfile.py
<localhost> EXEC /bin/sh -c 'chmod u+x /home/myuser/.ansible/tmp/ansible-tmp-1690445270.4359188-1858013-196186863923399/ /home/myuser/.ansible/tmp/ansible-tmp-1690445270.4359188-1858013-196186863923399/AnsiballZ_lineinfile.py && sleep 0'
<localhost> EXEC /bin/sh -c '/usr/bin/python3 /home/myuser/.ansible/tmp/ansible-tmp-1690445270.4359188-1858013-196186863923399/AnsiballZ_lineinfile.py && sleep 0'
<localhost> EXEC /bin/sh -c 'rm -f -r /home/myuser/.ansible/tmp/ansible-tmp-1690445270.4359188-1858013-196186863923399/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_ansible.builtin.lineinfile_payload_zzzkdvos/ansible_ansible.builtin.lineinfile_payload.zip/ansible/module_utils/basic.py", line 1700, in atomic_move
    os.rename(b_src, b_dest)
OSError: [Errno 18] Invalid cross-device link: b'/home/myuser/.ansible/tmp/ansible-tmp-1690445270.4359188-1858013-196186863923399/tmpjfbni7pj' -> b'/tmp/omam_osdx98l7y3m/extract/EFI/BOOT/BOOT.CFG'
failed: [X.X.X.X -> localhost] (item=/tmp/omam_osdx98l7y3m/extract/EFI/BOOT/BOOT.CFG) => {
    "ansible_loop_var": "item",
    "changed": false,
    "invocation": {
        "module_args": {
            "attributes": null,
            "backrefs": false,
            "backup": false,
            "create": false,
            "firstmatch": false,
            "group": null,
            "insertafter": null,
            "insertbefore": null,
            "line": "kernelopt=runweasel ks=cdrom:/KS.CFG",
            "mode": null,
            "owner": null,
            "path": "/tmp/omam_osdx98l7y3m/extract/EFI/BOOT/BOOT.CFG",
            "regexp": "^kernelopt=",
            "search_string": null,
            "selevel": null,
            "serole": null,
            "setype": null,
            "seuser": null,
            "state": "present",
            "unsafe_writes": false,
            "validate": null
        }
    },
    "item": "/tmp/omam_osdx98l7y3m/extract/EFI/BOOT/BOOT.CFG",
    "msg": "The destination directory (/tmp/omam_osdx98l7y3m/extract/EFI/BOOT) is not writable by the current user. Error was: [Errno 13] Permission denied: b'/tmp/omam_osdx98l7y3m/extract/EFI/BOOT/.ansible_tmp7a4ihbglBOOT.CFG'"
}
`

### Steps to Reproduce

Run the playbook

### Expected Behavior

Successfully copies the file and does the changes in KS

### Actual Behavior

Does not copy the kickstart file / access the file to continue with creating the ISO

### Screenshots

_No response_

### Additional Information

my user has rights to sudo and i do believe that tmp folder should have pretty relaxed rights in general.

### PR DESCRIPTION
**Pull request by Kritika-Bhateja-03**
…roles

# Description
A few sentences describing the overall goals of the pull request's commits.

# GitHub Issues
List the GitHub issues impacted by this PR:

| GitHub Issue # |
| -------------- |
| |

# ISSUE TYPE

- Bugfix Pull Request
- Docs Pull Request
- Feature Pull Request
- Test Pull Request

##### OUTPUT

```paste below

```
##### ADDITIONAL INFORMATION

```paste below

```
# Checklist:

- [ ] I have performed a self-review of my own code to ensure there are no formatting, vetting, linting, or security issues
- [ ] I have verified that new and existing unit tests pass locally with my changes
- [ ] I have not allowed coverage numbers to degenerate
- [ ] I have maintained at least 90% code coverage
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have maintained backward compatibility

### CODE REVIEW

**Comment by Kritika-Bhateja-03** [comment]
image
Screenshot attached for ansible lint report for below modules - 
idrac_server_powerstate
redfish_storage_volume

**Comment by ansible-collections-svc** [comment]
Can one of the admins verify this patch?

**Comment by Kritika-Bhateja-03** [comment]
image
Ansible lint report

**Comment by sachin-apa** [comment]
run e2e

**Review by ABHISHEK-SINHA10 — DISMISSED** [review]

**Review by ABHISHEK-SINHA10 — APPROVED** [review]

**Review by ShivamSh3 — APPROVED** [review]

**Review by Jennifer-John — APPROVED** [review]

**Review by singh-lovepreet1 — APPROVED** [review]

**Review by rajshekarp87 — APPROVED** [review]

**Pull request merged**
