### PR TITLE
[ome_diagnostics]: added changed flag in response

### LINKED ISSUE #394: ome_diagnostics result status misleading
##### Summary

Using 5.2.0 and the ome_diagnostics module.
When running in Run mode, after successfully extracting logs to a CIFS share, the result status shows OK.  This is misleading as OK with Ansible should indicate that no change was made because it was already in the state requested.  In this situation, logs were successfully created, so a change was made to the system, so the result should be "Changed"

When running the same module in Check mode, the result always shows "Changed" but in this case, nothing is actually being changed, so I would expect it to have a result of OK. (Edit: Actually, I would expect Changed, since outside of check_mode it would be making a change) I could be ok with this being Changed as it is assume that if it ran for real, it would change something, but I think OK would be a better indication that nothing happened.

##### Component Name

ome_diagnostics

##### Ansible Version

```paste below
ansible 2.10.17.post0
  config file = /runner/ansible.cfg
  configured module search path = ['/home/runner/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.8/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.8.12 (default, Sep 21 2021, 00:10:52) [GCC 8.5.0 20210514 (Red Hat 8.5.0-3)]
```

##### iDRAC or OpenManage Enterprise version

OME-M 1.40.10

##### Playbook used

```paste below
    - name: Extract Logs from MX7000 chassis to CIFS share location
      # https://github.com/dell/dellemc-openmanage-ansible-modules/blob/collections/docs/modules/ome_diagnostics.rst
      dellemc.openmanage.ome_diagnostics:
        hostname: "{{ inventory_hostname }}"
        username: "{{ dell_ome_username }}"
        password: "{{ dell_ome_password }}"
        validate_certs: "{{ dell_validate_certs | default(omit) }}"
        ca_path: "{{ dell_ca_path | default(omit) }}"
        share_type: CIFS
        share_address: "{{ cifs_server_ip }}"
        share_name: "{{ cifs_share }}{{ cifs_path | default(omit) }}"
        share_user: "{{ cifs_username }}"
        share_password: "{{ cifs_password }}"
        log_type: application
        lead_chassis_only: "{{ lead_chassis_only | default('true') }}"
        mask_sensitive_info: false
        job_wait: true

```

##### Expected Results

Running in real mode has a result of Change when a log bundle is created
Running in check mode as a result of OK since no new files were created or modified

#### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) 
  to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, 
  they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### PR DESCRIPTION
**Pull request by felixs88**
# Description
A few sentences describing the overall goals of the pull request's commits.

# GitHub Issues
List the GitHub issues impacted by this PR:

| GitHub Issue # |
| -------------- |
| |

# ISSUE TYPE

- Bugfix Pull Request
- Docs Pull Request
- Feature Pull Request
- Test Pull Request

##### OUTPUT

```paste below

```
##### ADDITIONAL INFORMATION

```paste below

```
# Checklist:

- [ ] I have performed a self-review of my own code to ensure there are no formatting, vetting, linting, or security issues
- [ ] I have verified that new and existing unit tests pass locally with my changes
- [ ] I have not allowed coverage numbers to degenerate
- [ ] I have maintained at least 90% code coverage
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have maintained backward compatibility

### CODE REVIEW

**Comment by ansible-collections-svc** [comment]
Can one of the admins verify this patch?

**Review by ABHISHEK-SINHA10 — APPROVED** [review]

**Review by ShivamSh3 — APPROVED** [review]

**Review by sachin-apa — APPROVED** [review]

**Comment by felixs88** [comment]
image

**Comment by felixs88** [comment]
image

**Comment by rajshekarp87** [comment]
Need to update corresponding rst file

**Comment by felixs88** [comment]
> Need to update corresponding rst file

Hi @rajshekarp87 -There is no RST file change here (Version or Copyright)

**Comment by rajshekarp87** [comment]
> > Need to update corresponding rst file
> 
> Hi @rajshekarp87 -There is no RST file change here (Version or Copyright)

Got it @felixs88

**Review by rajshekarp87 — APPROVED** [review]

**Pull request merged**
