### PR TITLE
Re-factor into a collection

### PR DESCRIPTION
**Pull request by mariolenz**
Since Ansible 2.9, the standard way to distribute ansible content are [collections](https://docs.ansible.com/ansible/2.9/dev_guide/developing_collections.html). I've started to re-factor your code into one.

There are still some things to do, especially updating the documentation. Oh, and there are problems with some unit tests but I'm not sure if this is really caused by the re-factoring or if the problems existed before.

This PR is the same as #120, only not for the devel but the collections branch.

### CODE REVIEW

**Comment by mariolenz** [comment]
@jagadeeshnv 

```
git clone https://github.com/mariolenz/dellemc-openmanage-ansible-modules.git
mkdir -p ansible_collections/dellemc
mv dellemc-openmanage-ansible-modules ansible_collections/dellemc/openmanage
cd ansible_collections/dellemc/openmanage
git checkout collection
ansible-test units --requirements
```
Result, at least at the moment: 2 failed, 1021 passed

**Comment by mariolenz** [comment]
@felixs88 @Sajna-Shetty You've committed some changes to both the master and devel branch... could you please update / re-base the collections branch as well? This would allow me to keep this PR up-to-date. thx

Btw: What's the difference between devel and master? Most projects I know have only one of them.

**Comment by mariolenz** [comment]
@jagadeeshnv 
> We created a new branch "collections" please submit it against that branch so that we can move forward.

I did, but I don't see you moving forward... I'd love to work with you on re-factoring your code into an ansible collection, but it looks like **you're** not interested. What do you say, do you want to work with me on this or not?

**Comment by jagadeeshnv** [comment]
> @jagadeeshnv
> 
> > We created a new branch "collections" please submit it against that branch so that we can move forward.
> 
> I did, but I don't see you moving forward... I'd love to work with you on re-factoring your code into an ansible collection, but it looks like **you're** not interested. What do you say, do you want to work with me on this or not?

Hi @mariolenz 
There are lot of files to be reviewed, Our team is going through it. Till now we have not found any comments for you. But before it officially goes into our repo, code has to be certified. We are on it, this will take some time.

**Comment by mariolenz** [comment]
Hi @jagadeeshnv 
> There are lot of files to be reviewed, Our team is going through it.

Yes, I know there are quite a lot of changes but re-factoring into a collection means all or nothing... and a big thank you for reviewing this PR at all! I really don't want to be offensive, it's just that it can be quite frustrating to not get any feedback at all.

For example, I'd really like to know about the two failed unit tests. Did the re-factoring break them or did they already fail before it?

And while there are a lot of files to review, the changes are (mostly) about moving stuff around and then fixing the imports, for example `ansible.modules.remote_management.dellemc -> ansible_collections.dellemc.openmanage.plugins.modules`.

> But before it officially goes into our repo, code has to be certified. We are on it, this will take some time.

Naturally. I don't want to hurry you, it's just that... well, not getting any feedback is- as said above- a bit frustrating, that's all. Like is it OK that I removed the deprecated modules or do you still want to keep them? I could change my PR accordingly if you want to.

**Comment by jagadeeshnv** [comment]
> For example, I'd really like to know about the two failed unit tests. Did the re-factoring break them or did they already fail before it?

No refactoring did not break it. When used with pytest it does not fail, ansible-test has stricter flags hence the failure. We fixed the 2 functions.

**Comment by jagadeeshnv** [comment]
Hi @mariolenz ,
Apologize for the delay. We were on it.
Thank you for your patience

As a first set of review comments, please look into the following.

1. Rename directory `examples` to `playbooks`.
2. Remove `guides` directory.
3. Remove `samples` directory. 
4. Remove the `tests/unit/compat` directory.
5. Remove the `tests/unit/utils.py` file.
6. Remove the empty directories `plugins/modules/idrac`, `plugins/modules/ome` and `plugins/modules/redfish`
7. Remove the directories `group_vars` and `host_vars`
8. Remove the files `CHANGELOG.md`, `CODING_GUIDELINES.md` and `CONTRIBUTOR_AGREEMENT.md`. We are yet to decide on it.

Note: Our plan is to release collections somewhere end of July 2020

**Comment by mariolenz** [comment]
> Apologize for the delay. We were on it.
> Thank you for your patience

No problem, I _did_ believe you when you said you're actively working on this. Naturally, since there's a lot of change this takes some time.

> As a first set of review comments, please look into the following. [...]

I'm sorry, but I'm not sure if I understand you... is this something I should do within this PR? Don't get me wrong, that wouldn't be a problem. I just want to be sure if this is something you expect me to do or not. Btw:

> 6. Remove the empty directories `plugins/modules/idrac`, `plugins/modules/ome` and `plugins/modules/redfish`

I don't see these directories in my branch. Actually, afaik git tracks files and not directories... so a directory without any content should simply vanish. If you really want to have an "empty" directory in git, I think the general workaround is to create an empty `.gitkeep` file in the directory and add it to the repository.

> Note: Our plan is to release collections somewhere end of July 2020

That would be really great!

**Comment by mariolenz** [comment]
@jagadeeshnv Why did you delete `galaxy.yml`? It's quite an important file because it more or less __defines__  the collection. No `galaxy.yml`, no collection as far as I understand:

> \# ansible-galaxy collection build
> ERROR! The collection galaxy.yml path '/ansible_collections/dellemc/openmanage/galaxy.yml' does not exist.
> \#

And some of the other files you've deleted seem to be important, too. At the moment, `ansible-test units [--requirements]` fails.

**Comment by jagadeeshnv** [comment]
We will be adding the galaxy.yml soon

**Comment by mariolenz** [comment]
> Kindly move the test files from tests/unit/* to tests/unit/plugins/*

done

**Comment by mariolenz** [comment]
@rajeevarakkal Running `ansible-test`, at least sometimes, results in files below `tests/output`. I've added `tests/.gitignore` to make git ignore these. They don't belong inside a repository ;-)

**Comment by jagadeeshnv** [comment]
@mariolenz 
We will be adding your name in Authors.md as 
- Mario Lenz (@mariolenz) 
Should be ok?

**Comment by mariolenz** [comment]
> We will be adding your name in Authors.md as
> 
>   Should be ok?

I didn't expect this, just wanted to help... so thank you very much for mentioning me in Authors.md :-)=)

**Comment by vvaldez** [comment]
Great job, this is very timely as I was just starting to explore the advantages of this repo vs. https://github.com/ansible-collections/community.general/tree/main/plugins/modules/remote_management/dellemc (will this replace it ever?). For now there are obviously way more features here, but the install was a but a bit overreaching. This collection is highly efficient alternative. For now I am using AWX (Tower) and decided instead of installing these modules system-wide, I just included the `library/dellemc/` out of here and placed it at my playbook level. +1 on this work!

**Comment by mariolenz** [comment]
@vvaldez 
> Great job, this is very timely as I was just starting to explore the advantages of this repo vs. https://github.com/ansible-collections/community.general/tree/main/plugins/modules/remote_management/dellemc (will this replace it ever?).

Personally, I think this repo should replace the iDRAC / OME modules in [community.general](https://github.com/ansible-collections/community.general) in the long run. This would both allow the ansible guys to focus on generic stuff (RedFish standard without any proprietary extensions) and Dell to develop and innovate their specific ansible modules independent from RedHat.

But that's just my personal opinion as a Dell customer and ansible user (and someone who has worked on several [ansible](https://github.com/ansible/ansible/commits?author=mariolenz) [modules](https://github.com/ansible-collections/vmware/commits?author=mariolenz)). I'm neither a Dell nor a RedHat employee and therefore don't have a... well, a vote or whatever you want to call it on this. I can only voice my opinion, but the developer team (or the product owner or whoever) has to decide this.

**Comment by jagadeeshnv** [comment]
@mariolenz 
We are merging this PR. Thank you

**Pull request merged**
