### PR TITLE
Re-add lost .gitignore

### PR DESCRIPTION
**Pull request by mariolenz**
@jagadeeshnv @felixs88 @Sajna-Shetty 

The collections branch doesn't have a `.gitignore`, seems it's been lost somewhere. That's an accident waiting to happen imho ;-)

### CODE REVIEW

**Comment by mariolenz** [comment]
@jagadeeshnv @felixs88 @Sajna-Shetty

I think you have to work on your communications a bit... you see, I can live with objections to this PR but not getting a reaction at all just sucks. I want to work with you, but I can't if you don't talk to me.

**Comment by jagadeeshnv** [comment]
> @jagadeeshnv @felixs88 @Sajna-Shetty
> 
> I think you have to work on your communications a bit... you see, I can live with objections to this PR but not getting a reaction at all just sucks. I want to work with you, but I can't if you don't talk to me.

@mariolenz Sorry about the delay. We will look into it and get back.

**Comment by mariolenz** [comment]
> Sorry about the delay. We will look into it and get back.

No problem, I'm a stubborn asshole and will keep asking you for an answer until I get one ;-P

I'm more concerned about other people who are not as stubborn as me. They might have some valuable inputs for you but give up working on them if they don't get a timely answer. In the long run, people might even refrain from opening issues or PRs and that means you're loosing the contact to your users. To put it bluntly: You'll end up working on features and bugs that you or your managers think important, but your users and customers don't.

**Comment by mariolenz** [comment]
@jagadeeshnv C'mon guys, we're talking about `.gitignore` and not about rocket science. I'm not proposing a completely untested change to a critical part of software that prevents your nuclear power plant from polluting half a continent.

If you think artifacts like `*.py[co]` or test outputs belong into a source code repository, you're free to close this PR instead of merging it. You would be wrong, though...

**Review by anupamaloke — APPROVED** [review]
LGTM

**Comment by anupamaloke** [comment]
@jagadeeshnv, could you please merge the changes?

**Comment by rajeevarakkal** [comment]
@mariolenz we are merging this change.

**Pull request merged**
