### PR TITLE
[ome_firmware]: Added reboot_type option to the module.

### LINKED ISSUE #505: [FEATURE]: Add reboot options to module dellemc.openmanage.ome_firmware
**Describe the solution you'd like**
Most firmware updates require a reboot. When the ansible module `dellemc.openmanage.ome_firmware` is used to update firmware, it is possible to use the `schedule` parameter to schedule the necessary reboot to `RebootNow` or `StageForNextReboot`. However when `RebootNow` is used, I have not found a way to specify the type of reboot.

In the Dell OpenManage Enterprise web interface there are three different types of immediate reboots in the "Device Compliance Dialog":
- Graceful Reboot with Forced Shutdown
- Graceful Reboot without Forced Shutdown
- Power Cycle

For me it currently looks like "Power Cycle" is always used when `RebootNow` is selected as the firmware update schedule. It would be great if the `dellemc.openmanage.ome_firmware module` enabled the users to select which type of reboot they would prefer in their ansible scripts.

**Describe alternatives you've considered**
If a graceful reboot should be achieved, the `schedule` parameter could be set to `StageForNextReboot` and another task added to the playbook in which the target system is rebooted with the `ansible.builtin.reboot` module. However for this to work, credentials for the target system are required whereas the `dellemc.openmanage.ome_firmware` module only requires credentials for Dell OpenManage Enterprise.

**Additional context**
Maybe I am wrong and the default reboot type is not `power cycle` or the reboot type can be specified. I would appreciate an according feedback.

**Community Note**
* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) 
  to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, 
  they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### PR DESCRIPTION
**Pull request by ABHISHEK-SINHA10**
# Description
A few sentences describing the overall goals of the pull request's commits.

# GitHub Issues
List the GitHub issues impacted by this PR:

| GitHub Issue # |
| -------------- |
| #505 |

# ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
ome_firmware

# Checklist:

- [x] I have performed a self-review of my own code to ensure there are no formatting, vetting, linting, or security issues
- [x] I have verified that new and existing unit tests pass locally with my changes
- [x] I have not allowed coverage numbers to degenerate
- [x] I have maintained at least 90% code coverage
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have maintained backward compatibility

### CODE REVIEW

**Comment by ansible-collections-svc** [comment]
Can one of the admins verify this patch?

**Review by sachin-apa — DISMISSED** [review]
Looks good ..

**Review by Kritika-Bhateja-03 — DISMISSED** [review]

**Review by jagadeeshnv — DISMISSED** [review]

**Comment by ABHISHEK-SINHA10** [comment]
**AV-OMAM:**
image

**CX-OMAM:**
image

**BD-OMAM:**
image

**Comment by ABHISHEK-SINHA10** [comment]
**SONAR:**
image

**Review by ShivamSh3 — DISMISSED** [review]

**Review by jagadeeshnv — APPROVED** [review]

**Review by felixs88 — APPROVED** [review]

**Review by Jennifer-John — APPROVED** [review]

**Comment by Jennifer-John** [comment]
Verification completed.

**Pull request merged**
