### PR TITLE
Adding Dockerfile and README for collections branch

### PR DESCRIPTION
**Pull request by saishivarcr**

### CODE REVIEW

**Review by jagadeeshnv — APPROVED** [review]

**Review by jagadeeshnv — CHANGES_REQUESTED** [review]
Not sure collection it can be added

**Comment by sameer1046** [comment]
Can one of the admins verify this patch?

**Comment by ansible-collections-svc** [comment]
Can one of the admins verify this patch?

**Comment by sachin-apa** [comment]
Closing the PR as this is achieved using an Execution Environment in Ansible using ansible builder.

**Pull request closed without merging**
